
# Spring DataSource (MySQL)


# awsMysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://ec2-3-34-117-56.ap-northeast-2.compute.amazonaws.com/dailydb
spring.datasource.url=jdbc:mysql://ec2-3-37-155-254.ap-northeast-2.compute.amazonaws.com/kara
spring.datasource.username=kara
spring.datasource.password=kara


# Spring JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=false


coolsms.api.key=NCSFWQ97LWPZPI27
coolsms.api.secret=COPNSNNBJ61AOXXLUEERL4K9KA4SWJ9O

server.port=7713


#GoolgSmtp
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dailytalkky@gmail.com
spring.mail.password=iuyzvajvxvowumja
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



#aws-key
#cloud.aws.credentials.accessKey=AKIAUSX3B3YICZTVXCOF
#cloud.aws.credentials.secretKey=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
cloud.aws.credentials.accessKey=AKIAU6GDXUGTPM5X2A6A
cloud.aws.credentials.secretKey=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
cloud.aws.stack.auto=false

#aws(s3)
cloud.aws.s3.bucket=dailytalkbucket
cloud.aws.region.static=ap-northeast-2
s3.base-url=https://dailytalkbucket.s3.ap-northeast-2.amazonaws.com/


# upload max range
spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=100MB


#Kakao Login service
kakao.client.id=d6389052ff39df26be576d96bbf477e4
kakao.redirect.url=http://dailytalk:7713/member/kakao/callback


